services:
  - type: web
    name: ocr-translate-bot
    env: python
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    nativePackages:
      - poppler-utils
      - libgl1
      - libglib2.0-0
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
